[font]
size = 15.0

[font.offset]
x = 0
y = 0

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "ExtraLight"

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Light"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "ExtraLight Italic"

[colors.normal]
red = "0xff8888"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Command"

# Prevent accidental closing of the window
[[keyboard.bindings]]
action = "None"
key = "w"
mods = "Command"

# This stopped working for Alacritty a while ago
# [[keyboard.bindings]]
# action = "None"
# key = "q"
# mods = "Command"

# Make <c-cr> mappable in Neovim, from https://erwin.co/getting-ctrltab-to-work-in-neovim/
[[keyboard.bindings]]
chars = "\u001b[13;5u"
key = "Return"
mods = "Control"

# Hide window title bar
[window]
decorations = "None"
startup_mode = "Maximized"

# Copy selected text to the primary clipboard
[selection]
  save_to_clipboard = true
